/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ResultList: typeof import('./src/components/ResultList.vue')['default']
    ResultRow: typeof import('./src/components/ResultRow.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanNotify: typeof import('vant/es')['Notify']
  }
}

// For TSX support
declare global {
  const ResultList: typeof import('./src/components/ResultList.vue')['default']
  const ResultRow: typeof import('./src/components/ResultRow.vue')['default']
  const SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  const TopBar: typeof import('./src/components/TopBar.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanDropdownItem: typeof import('vant/es')['DropdownItem']
  const VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanNotify: typeof import('vant/es')['Notify']
}